import { useEffect, useRef, useState } from 'react'
import { mfaLabel } from './userStatus.js'

function ConfirmDialog({ config, busy, onCancel, onConfirm }) {
  const cancelRef = useRef(null)
  useEffect(() => { cancelRef.current?.focus() }, [])
  useEffect(() => { const fn = (e) => { if (e.key === 'Escape' && !busy) onCancel() }; document.addEventListener('keydown', fn); return () => document.removeEventListener('keydown', fn) }, [busy, onCancel])
  return <div className="admin-dialog-backdrop" role="presentation" onMouseDown={(e) => { if (e.target === e.currentTarget && !busy) onCancel() }}><div className="admin-dialog" role="alertdialog" aria-modal="true" aria-labelledby="admin-confirm-title" aria-describedby="admin-confirm-copy"><h2 id="admin-confirm-title">{config.title}</h2><p id="admin-confirm-copy">{config.copy}</p><div className="admin-dialog-actions"><button ref={cancelRef} type="button" className="admin-button secondary" disabled={busy} onClick={onCancel}>İptal</button><button type="button" className={`admin-button ${config.danger ? 'danger' : ''}`} disabled={busy} onClick={onConfirm}>{busy ? 'İşleniyor…' : config.action}</button></div></div></div>
}

export default function UserDetailPanel({ user, currentUserId, loading, mutating, onClose, onChangeRole, onChangeStatus }) {
  const [confirm, setConfirm] = useState(null)
  useEffect(() => { const fn = (e) => { if (e.key === 'Escape' && !confirm) onClose() }; document.addEventListener('keydown', fn); return () => document.removeEventListener('keydown', fn) }, [confirm, onClose])
  const requestRole = (role) => setConfirm({ kind: 'role', value: role, title: `${user.username} kullanıcısının rolü ${role} olsun mu?`, copy: role === 'Admin' ? 'Admin rolü kullanıcı yönetimi ve tüm çizimler üzerinde yönetim yetkisi sağlar. 2FA kapalıysa kullanıcı sonraki girişinde kurulum yapmalıdır.' : `Bu kullanıcı yönetici yetkilerini kaybedecek.${user.id === currentUserId ? ' Kendi hesabınızı değiştiriyorsunuz; mevcut oturum kısa süre eski yetkileri taşıyabilir.' : ''}`, action: role === 'Admin' ? 'Admin Yap' : 'User Yap', danger: role === 'User' })
  const requestStatus = (active) => setConfirm({ kind: 'status', value: active, title: `${user.username} hesabı ${active ? 'aktifleştirilsin' : 'pasifleştirilsin'} mi?`, copy: active ? 'Rol, e-posta doğrulaması, 2FA ve çizim sahipliği değişmeden hesap yeniden giriş yapabilir.' : `Kullanıcı yeni oturum açamayacaktır. Mevcut çizimleri silinmeyecek ve haritada kalacaktır.${user.id === currentUserId ? ' Kendi hesabınızı pasifleştiriyorsunuz.' : ''}`, action: active ? 'Hesabı Aktifleştir' : 'Hesabı Pasifleştir', danger: !active })
  const submit = async () => { const next = confirm; if (next.kind === 'role') await onChangeRole(next.value); else await onChangeStatus(next.value); setConfirm(null) }
  return <><div className="admin-panel-scrim" onMouseDown={onClose} aria-hidden="true" /><aside className="admin-detail-panel" role="dialog" aria-modal="true" aria-labelledby="admin-detail-title"><button type="button" className="admin-panel-close" onClick={onClose} aria-label="Detayı kapat">×</button>{loading || !user ? <div className="admin-detail-loading">Kullanıcı detayı yükleniyor…</div> : <><header><span className="admin-avatar" aria-hidden="true">{user.username.slice(0, 1).toUpperCase()}</span><div><h2 id="admin-detail-title">{user.username}</h2>{user.id === currentUserId && <span className="admin-badge info">Siz</span>}</div></header><dl className="admin-detail-grid"><div><dt>Kullanıcı adı</dt><dd>{user.username}</dd></div><div><dt>E-posta</dt><dd>{user.email || '—'}</dd></div><div><dt>E-posta durumu</dt><dd>{user.emailConfirmed ? 'Doğrulandı' : 'Doğrulanmadı'}</dd></div><div><dt>İki Faktörlü Doğrulama</dt><dd>{mfaLabel(user)}</dd></div><div><dt>Son güncelleme</dt><dd>{new Intl.DateTimeFormat('tr-TR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(user.modifiedDate))}</dd></div></dl><section className="admin-management"><h3>Yetki ve hesap durumu</h3><label>Rol<select value={user.role || 'User'} disabled={mutating} onChange={(e) => requestRole(e.target.value)}><option value="User">User</option><option value="Admin">Admin</option></select></label><label>Hesap Durumu<select value={user.isActive ? 'active' : 'inactive'} disabled={mutating} onChange={(e) => requestStatus(e.target.value === 'active')}><option value="active">Aktif</option><option value="inactive">Pasif</option></select></label>{user.role === 'Admin' && <p className="admin-policy-note">Sistemde en az bir aktif yönetici bulunmalıdır. Son aktif Admin’in rolü düşürülemez veya hesabı pasifleştirilemez.</p>}<p className="admin-readonly-note">E-posta doğrulaması ve 2FA durumu yalnızca görüntülenir. Parola ve güvenlik anahtarlarına erişilemez.</p></section></>}</aside>{confirm && <ConfirmDialog config={confirm} busy={mutating} onCancel={() => setConfirm(null)} onConfirm={submit} />}</>
}
